Library Imports

In [82]:
import numpy as np
import pandas as pd
import requests
import xlsxwriter
import math

Importing Our List of Stocks

In [4]:
stocks=pd.read_csv('sp_500_stocks.csv')

In [5]:
stocks.head()

  Ticker
0      A
1    AAL
2    AAP
3   AAPL
4   ABBV

In [6]:
type(stocks)

pandas.core.frame.DataFrame

In [7]:
stocks.describe

<bound method NDFrame.describe of     Ticker
0        A
1      AAL
2      AAP
3     AAPL
4     ABBV
5      ABC
6     ABMD
7      ABT
8      ACN
9     ADBE
10     ADI
11     ADM
12     ADP
13    ADSK
14     AEE
15     AEP
16     AES
17     AFL
18     AIG
19     AIV
20     AIZ
21     AJG
22    AKAM
23     ALB
24    ALGN
25     ALK
26     ALL
27    ALLE
28    ALXN
29    AMAT
..     ...
475     VZ
476    WAB
477    WAT
478    WBA
479    WDC
480    WEC
481   WELL
482    WFC
483    WHR
484   WLTW
485     WM
486    WMB
487    WMT
488    WRB
489    WRK
490    WST
491     WU
492     WY
493   WYNN
494    XEL
495   XLNX
496    XOM
497   XRAY
498    XRX
499    XYL
500    YUM
501    ZBH
502   ZBRA
503   ZION
504    ZTS

[505 rows x 1 columns]>

API Token

In [8]:
IEX_CLOUD_API_TOKEN='Tpk_059b97af715d417d9f49f50b51b1c448'

Making Our First API Call

In [9]:
symbol='AAPL'
api_url=f'https://sandbox.iexapis.com/stable/stock/{symbol}/quote/?token={IEX_CLOUD_API_TOKEN}'
print(api_url)


data=requests.get(api_url).json()
print(data)

https://sandbox.iexapis.com/stable/stock/AAPL/quote/?token=Tpk_059b97af715d417d9f49f50b51b1c448
{'symbol': 'AAPL', 'companyName': 'Apple Inc', 'primaryExchange': 'G)NASDN/LA L  ESLETQAOKRCBTAE(MSG', 'calculationPrice': 'close', 'open': 128.45, 'openTime': 1651904808808, 'openSource': 'aiffiloc', 'close': 132.38, 'closeTime': 1683482565048, 'closeSource': 'fiafiolc', 'high': 133.52, 'highTime': 1642877066633, 'highSource': 'elicedey ei at5rup1d mn', 'low': 129.82, 'lowTime': 1614684373004, 'lowSource': ' ncute1apiyeeri5 ld med', 'latestPrice': 134.95, 'latestSource': 'Close', 'latestTime': 'January 7, 2021', 'latestUpdate': 1635990818061, 'latestVolume': 113697082, 'iexRealtimePrice': 135.4, 'iexRealtimeSize': 19, 'iexLastUpdated': 1683811573816, 'delayedPrice': 133.15, 'delayedPriceTime': 1679592392584, 'oddLotDelayedPrice': 132.687, 'oddLotDelayedPriceTime': 1629575066867, 'extendedPrice': 137.9, 'extendedChange': 0.77, 'extendedChangePercent': 0.00598, 'extendedPriceTime': 1688232262530, 'previousClose': 130.8, 'previousVolume': 159835460, 'change': 4.38, 'changePercent': 0.03564, 'volume': 112531286, 'iexMarketPercent': 0.013502475691820311, 'iexVolume': 1476389, 'avgTotalVolume': 115345775, 'iexBidPrice': 0, 'iexBidSize': 0, 'iexAskPrice': 0, 'iexAskSize': 0, 'iexOpen': 133.89, 'iexOpenTime': 1664523433379, 'iexClose': 134.65, 'iexCloseTime': 1653317896483, 'marketCap': 2281784453545, 'peRatio': 40.21, 'week52High': 141.83, 'week52Low': 56.46, 'ytdChange': 0.02134454996381987, 'lastTradeTime': 1633864898087, 'isUSMarketOpen': False}

Parsing Our API Call

In [10]:
price=data['latestPrice']
print(price)
market_cap=data['marketCap']
print(market_cap/1000000000000)

134.95
2.281784453545

Adding Our Stocks Data to a Pandas DataFrame

In [55]:
my_columns=['Ticker', 'Stock_Price', 'Market_Cap', 'Number Of Shares to Buy']
final_dataframe=pd.DataFrame(columns=my_columns)
final_dataframe

Empty DataFrame
Columns: [Ticker, Stock_Price, Market_Cap, Number Of Shares to Buy]
Index: []

In [56]:
final_dataframe.append(
    pd.Series(
    [
        symbol,
        price,
        market_cap,
        'N/A'
        
    ],
        index=my_columns,
    ),
    
    ignore_index=True

)

  Ticker  Stock_Price     Market_Cap Number Of Shares to Buy
0    ZTS       134.95  2281784453545                     N/A

Looping Through The Tickers in Our List of Stocks

In [58]:
final_dataframe=pd.DataFrame(columns=my_columns)
for stock in stocks['Ticker']:
#     print(df)
    api_url=f'https://sandbox.iexapis.com/stable/stock/{stock}/quote/?token={IEX_CLOUD_API_TOKEN}'
    data=requests.get(api_url).json()
    final_dataframe=final_dataframe.append(
        pd.Series(
        [
            stock,
            data['latestPrice'],
            data['marketCap'],
            'N/A'
        
        ],index=my_columns),
    ignore_index=True
    )

In [59]:
final_dataframe

    Ticker  Stock_Price     Market_Cap Number Of Shares to Buy
0        A       131.82    40198987870                     N/A
1      AAL        15.39     9671269016                     N/A
2      AAP       169.08    11531317609                     N/A
3     AAPL       136.24  2238913695673                     N/A
4     ABBV       111.90   197126608105                     N/A
5      ABC       115.42    22853502851                     N/A
6     ABMD       336.53    14989797634                     N/A
7      ABT       114.80   201132737413                     N/A
8      ACN       270.40   180840287641                     N/A
9     ADBE       490.06   233160956342                     N/A
10     ADI       157.14    59128060056                     N/A
11     ADM        53.20    30470090632                     N/A
12     ADP       170.09    73626760351                     N/A
13    ADSK       329.10    72132521820                     N/A
14     AEE        77.10    18989373684                     N/A
15     AEP        82.20    40177155245                     N/A
16     AES        25.40    16931343928                     N/A
17     AFL        45.73    32599137631                     N/A
18     AIG        42.09    35397239297                     N/A
19     AIV         5.11      784335432                     N/A
20     AIZ       142.34     8386475104                     N/A
21     AJG       128.23    24183548002                     N/A
22    AKAM       105.39    16913114092                     N/A
23     ALB       189.00    19927944666                     N/A
24    ALGN       573.27    44417986574                     N/A
25     ALK        53.61     6543086701                     N/A
26     ALL       114.37    34109227768                     N/A
27    ALLE       122.90    11514299708                     N/A
28    ALXN       161.21    35171524263                     N/A
29    AMAT        97.30    88616607776                     N/A
..     ...          ...            ...                     ...
475     VZ        58.79   252444630799                     N/A
476    WAB        84.41    16132319588                     N/A
477    WAT       267.08    16611871528                     N/A
478    WBA        45.30    40847016475                     N/A
479    WDC        56.05    17216166621                     N/A
480    WEC        88.86    28492754697                     N/A
481   WELL        64.00    27162096869                     N/A
482    WFC        33.77   139989446878                     N/A
483    WHR       190.82    11747460232                     N/A
484   WLTW       214.70    26948667157                     N/A
485     WM       123.85    51960725388                     N/A
486    WMB        22.22    26767031855                     N/A
487    WMT       149.79   423543855456                     N/A
488    WRB        68.93    12318483945                     N/A
489    WRK        47.18    12302196394                     N/A
490    WST       308.74    22803180841                     N/A
491     WU        23.11     9557961796                     N/A
492     WY        34.41    26208176178                     N/A
493   WYNN       109.96    12037254707                     N/A
494    XEL        65.94    35399163575                     N/A
495   XLNX       156.31    37559887770                     N/A
496    XOM        47.20   190856215434                     N/A
497   XRAY        59.45    12797759602                     N/A
498    XRX        23.67     4826907293                     N/A
499    XYL       110.77    20448326238                     N/A
500    YUM       107.90    32028362542                     N/A
501    ZBH       162.40    33597168681                     N/A
502   ZBRA       419.50    22033563853                     N/A
503   ZION        50.04     8269049335                     N/A
504    ZTS       168.00    80567431776                     N/A

[505 rows x 4 columns]

Using Batch API Calls to Improve Performance

In [60]:
def divide_chunks(lst, n): 
      
    
    for i in range(0, len(lst), n):  
        yield lst[i:i + n]

In [61]:
symbol_groups=list(divide_chunks(stocks['Ticker'], 100))
symbol_strings=[]
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
#     print(symbol_strings[i])
final_dataframe=pd.DataFrame(columns=my_columns)
for symbol_string in symbol_strings:
    batch_api_call_url=f'https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol_string}&types=quote&token={IEX_CLOUD_API_TOKEN}'
    data=requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        final_dataframe=final_dataframe.append(
            pd.Series(
            [
                symbol,
                data[symbol]['quote']['latestPrice'],
                data[symbol]['quote']['marketCap'],
                'N/A'
            ], 
                index=my_columns), 
                ignore_index=True
            )
        
final_dataframe

    Ticker  Stock_Price     Market_Cap Number Of Shares to Buy
0        A       131.34    40590962836                     N/A
1      AAL        16.15     9695930398                     N/A
2      AAP       175.50    11807454064                     N/A
3     AAPL       134.84  2203376618228                     N/A
4     ABBV       110.03   188460160024                     N/A
5      ABC       110.39    23281047652                     N/A
6     ABMD       338.73    15295097226                     N/A
7      ABT       113.00   202770122287                     N/A
8      ACN       266.10   182184096691                     N/A
9     ADBE       488.42   232995104075                     N/A
10     ADI       157.09    58791937999                     N/A
11     ADM        52.93    29666512625                     N/A
12     ADP       170.85    73468064146                     N/A
13    ADSK       324.70    71112787398                     N/A
14     AEE        76.45    18578177171                     N/A
15     AEP        81.91    40335048141                     N/A
16     AES        25.71    16774790385                     N/A
17     AFL        45.83    32887838980                     N/A
18     AIG        42.89    36431176989                     N/A
19     AIV         5.08      788487957                     N/A
20     AIZ       143.45     8495547450                     N/A
21     AJG       128.01    23946748855                     N/A
22    AKAM       107.63    16954807428                     N/A
23     ALB       187.00    19758852535                     N/A
24    ALGN       566.61    45563125433                     N/A
25     ALK        52.73     6604311579                     N/A
26     ALL       114.52    34330646285                     N/A
27    ALLE       124.70    11184845926                     N/A
28    ALXN       158.74    35641325346                     N/A
29    AMAT        95.61    89130643538                     N/A
..     ...          ...            ...                     ...
475     VZ        60.65   250235045139                     N/A
476    WAB        85.61    15743555934                     N/A
477    WAT       270.10    16522499186                     N/A
478    WBA        45.44    39608042163                     N/A
479    WDC        54.75    17054377350                     N/A
480    WEC        90.03    28686803254                     N/A
481   WELL        63.80    27414295685                     N/A
482    WFC        34.49   140756555916                     N/A
483    WHR       185.72    11526439651                     N/A
484   WLTW       212.80    26466709567                     N/A
485     WM       118.38    52156670460                     N/A
486    WMB        22.43    26968910849                     N/A
487    WMT       147.65   417826836378                     N/A
488    WRB        66.58    12305606548                     N/A
489    WRK        46.68    12612998979                     N/A
490    WST       311.29    23397415446                     N/A
491     WU        23.79     9799455540                     N/A
492     WY        34.82    25805555178                     N/A
493   WYNN       115.16    12052602674                     N/A
494    XEL        66.51    34286058517                     N/A
495   XLNX       150.92    38446162070                     N/A
496    XOM        45.71   193929452284                     N/A
497   XRAY        59.62    12745084524                     N/A
498    XRX        23.79     4681807223                     N/A
499    XYL       109.57    19960720642                     N/A
500    YUM       106.20    32923650787                     N/A
501    ZBH       167.10    34463232328                     N/A
502   ZBRA       427.60    21878470131                     N/A
503   ZION        51.12     8358665741                     N/A
504    ZTS       167.00    81780646956                     N/A

[505 rows x 4 columns]

Calculating the Number of Shares to Buy

In [62]:
portfolio_size=input('Enter the value of your portfolio: ')
try:
    val=float(portfolio_size)

except ValueError:
    print("That's not a number!!\nPlease try again..")
    portfolio_size=input('Enter the value of your portfolio: ')
    val=float(portfolio_size)

Enter the value of your portfolio: 1000000

In [89]:
position_size=val/len(final_dataframe.index)
for i in range(0, len(final_dataframe['Ticker'])-1):
    final_dataframe.loc[i, 'Number Of Shares to Buy'] = math.floor(position_size / final_dataframe.loc[i,'Stock_Price'])
final_dataframe
# number_of_apple_shares=position_size/500
# print(math.floor(number_of_apple_shares))

    Ticker  Stock_Price     Market_Cap Number Of Shares to Buy
0        A       131.34    40590962836                      15
1      AAL        16.15     9695930398                     122
2      AAP       175.50    11807454064                      11
3     AAPL       134.84  2203376618228                      14
4     ABBV       110.03   188460160024                      17
5      ABC       110.39    23281047652                      17
6     ABMD       338.73    15295097226                       5
7      ABT       113.00   202770122287                      17
8      ACN       266.10   182184096691                       7
9     ADBE       488.42   232995104075                       4
10     ADI       157.09    58791937999                      12
11     ADM        52.93    29666512625                      37
12     ADP       170.85    73468064146                      11
13    ADSK       324.70    71112787398                       6
14     AEE        76.45    18578177171                      25
15     AEP        81.91    40335048141                      24
16     AES        25.71    16774790385                      77
17     AFL        45.83    32887838980                      43
18     AIG        42.89    36431176989                      46
19     AIV         5.08      788487957                     389
20     AIZ       143.45     8495547450                      13
21     AJG       128.01    23946748855                      15
22    AKAM       107.63    16954807428                      18
23     ALB       187.00    19758852535                      10
24    ALGN       566.61    45563125433                       3
25     ALK        52.73     6604311579                      37
26     ALL       114.52    34330646285                      17
27    ALLE       124.70    11184845926                      15
28    ALXN       158.74    35641325346                      12
29    AMAT        95.61    89130643538                      20
..     ...          ...            ...                     ...
475     VZ        60.65   250235045139                      32
476    WAB        85.61    15743555934                      23
477    WAT       270.10    16522499186                       7
478    WBA        45.44    39608042163                      43
479    WDC        54.75    17054377350                      36
480    WEC        90.03    28686803254                      21
481   WELL        63.80    27414295685                      31
482    WFC        34.49   140756555916                      57
483    WHR       185.72    11526439651                      10
484   WLTW       212.80    26466709567                       9
485     WM       118.38    52156670460                      16
486    WMB        22.43    26968910849                      88
487    WMT       147.65   417826836378                      13
488    WRB        66.58    12305606548                      29
489    WRK        46.68    12612998979                      42
490    WST       311.29    23397415446                       6
491     WU        23.79     9799455540                      83
492     WY        34.82    25805555178                      56
493   WYNN       115.16    12052602674                      17
494    XEL        66.51    34286058517                      29
495   XLNX       150.92    38446162070                      13
496    XOM        45.71   193929452284                      43
497   XRAY        59.62    12745084524                      33
498    XRX        23.79     4681807223                      83
499    XYL       109.57    19960720642                      18
500    YUM       106.20    32923650787                      18
501    ZBH       167.10    34463232328                      11
502   ZBRA       427.60    21878470131                       4
503   ZION        51.12     8358665741                      38
504    ZTS       167.00    81780646956                     N/A

[505 rows x 4 columns]

In [100]:
writer=pd.ExcelWriter('recommended trades.xlsx', engine='xlsxwriter')
final_dataframe.to_csv(sheet_name='recommended trades', index=False)